### ISSUE TITLE
japanese.ini still requires the "Author" field

### ISSUE THREAD

**Issue by Lojemiru** [Lojemiru/AM2R-Localizations#1]
The "Author" field under [OptionsDisplay] determines the word used to credit the translator(s) for a given localization. This word could be "Author," "Translator," "Localizer," or a similar term in your native language.

[Google Translate]

[OptionsDisplay]の下の[Author]フィールドは、特定のローカリゼーションの翻訳者にクレジットを付与するために使用される単語を決定します。この単語は、「作成者」、「翻訳者」、「ローカライザー」、または母国語の同様の用語である可能性があります。

**Comment by ponyexs** [comment]
I'm gponys.
I filled in [Author].
